### ISSUE TITLE
Slides not swiping on mobiles

### ISSUE THREAD

**Issue by junkystu** [jedrzejchalubek/Glide.js#127] opened 2015-11-07 23:55 UTC
I am unable to change to previous and next slides on mobile.

Create a slideshow using default settings and drag the current image slide with your mouse, left and right, and slides will change - works as expected. 

Using Chrome, open developer tools and enable device mode/emulate by clicking the mobile phone icon and then try doing the same thing using mouse, slides do not change.

The issue also occurs on Galaxy S5 Android 4.4.2

**Comment by jedrzejchalubek** [comment] 2015-11-08 11:59
I've spot the bug, will be fixed in next commit. The problem is that `.glide__track` where swipe events are binded, don't have height on mobile devices.

For now u can init plugin with `autoheight: true` option, this should fix it.

**Comment by junkystu** [comment] 2015-11-08 17:46
Awesome, that works too. Thanks for looking into it :)

**Closed** 2015-11-10 16:19 UTC
Labels: bug, has-patch
